### ISSUE TITLE
CUDA_DISABLE_CONTROL=true has no effect — HAMI still hijacks GPU behavior

### ISSUE THREAD

**Issue by bestend** [Project-HAMi/HAMi#1050]
**Description:**

Hi,

I’m currently running a container with the following setup:

* GPU: NVIDIA L40S
* Driver version: 570.124.06
* CUDA version: 12.8

Even when I set `CUDA_DISABLE_CONTROL=true`, I’m seeing that `hami` still hijacks control of the GPU and outputs messages like:

```
[HAMI-core Msg]: Initializing.....
[HAMI-core Msg]: Calling exit handler
```

As shown in `nvidia-smi`, HAMI seems to remain active:

```
root@model-d6fb5dbc5-d2t7p:/workspace# env | grep CUDA_DISABLE_CONTROL
CUDA_DISABLE_CONTROL=true
root@model-d6fb5dbc5-d2t7p:/workspace# nvidia-smi
[HAMI-core Msg(417:139803620223872:libvgpu.c:836)]: Initializing.....
Wed May 14 21:23:40 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    On  |   00000000:3F:00.0 Off |                    0 |
| N/A   42C    P0             84W /  350W |     970MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
[HAMI-core Msg(417:139803620223872:multiprocess_memory_limit.c:501)]: Calling exit handler 417
```

**Question:**
Is there a proper way to fully disable HAMI behavior inside containers?
Setting `CUDA_DISABLE_CONTROL=true` does not appear to work.

Thanks in advance for your help!

**Environment**:
- HAMi version: 2.5.1
- Kubernetes version: v1.28.10+rke2r1
- Others:

**Comment by Nimbus318** [comment]
Hi @bestend,

For `CUDA_DISABLE_CONTROL=true` to take effect and properly disable HAMi behavior, it needs to be set as an environment variable when the container is being created, for example, within the Pod's manifest `env` section. This is because this logic is  handled by the device plugin. Consequently, setting it manually inside an already running container won't have the intended effect.

**Comment by bestend** [comment]
Hi @Nimbus318 ,

The result you mentioned is based on the configuration defined in the Pod's manifest env section.

**Comment by Nimbus318** [comment]
Hi @bestend,

May I ask if any related configuration was modified during the installation of HAMi? We've tested that setting `CUDA_DISABLE_CONTROL` to `"true"` in the container env does correctly disable HAMi behavior.

The relevant code logic can be found here:
https://github.com/Project-HAMi/HAMi/blob/6218d7e4a0c1a42644fb8a89e5e3cbcf6f5d1133/pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go#L486-L503

Could you share any configuration values that were customized when installing HAMi?

**Comment by bestend** [comment]
Hi @Nimbus318 

I’m using the Helm chart version 2.5.1, and my values.yaml is configured as follows:

```yaml
scheduler:
  # @param nodeName defines the node name and the nvidia-vgpu-scheduler-scheduler will schedule to the node.
  # if we install the nvidia-vgpu-scheduler-scheduler as default scheduler, we need to remove the k8s default
  # scheduler pod from the cluster first, we must specify node name to skip the schedule workflow.
  nodeName: ""
  #    "gpu": "on"
  defaultMem: 0
  defaultCores: 0
  defaultGPUNum: 1
  overwriteEnv: "false"
  defaultSchedulerPolicy:
    nodeSchedulerPolicy: spread
    gpuSchedulerPolicy: spread
  metricsBindAddress: ":9395"
  livenessProbe: false
  leaderElect: true
  kubeScheduler:
    # @param enabled indicate whether to run kube-scheduler container in the scheduler pod, it's true by default.
    enabled: true
    imageTag: "v1.28.10" # server version에 맞춰서 기입
#    image: harbor.hmc.co.kr/hydra/google_containers/kube-scheduler
    imagePullPolicy: IfNotPresent
    extraNewArgs:
      - --config=/config/config.yaml
      - -v=4
    extraArgs:
      - --policy-config-file=/config/config.json
      - -v=4

devicePlugin:
  passDeviceSpecsEnabled: false
  nvidianodeSelector:
    gpu: null
    hami: "true"
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
```

**Comment by bestend** [comment]
@Nimbus318 

I’ve found the cause.
In the Linkerd service mesh we’re using, a proxy sidecar is injected,
and I confirmed that the following code checks the proxy sidecar’s environment variables.

Is there any room for improvement?

https://github.com/Project-HAMi/HAMi/blob/dceded040065cdd8c1cd477d5998ab690a3036e3/pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go#L562

**Comment by Nimbus318** [comment]
@bestend Thanks for clarifying! Just to check if I got your point right: you mean HAMi might have mis-handled the multi-container Pod case — seeing that the `linkerd-proxy` sidecar has no `CUDA_DISABLE_CONTROL` env, and then mistakenly injecting `/etc/ld.so.preload` into the gpu container?

From what I see in the current code, HAMi should already handle multi-container Pods correctly:

* it decodes the device request annotation,
* finds the exact container that requested GPU (`p.Spec.Containers[ctridx]`),
* and checks **that container’s** env (`currentCtr.Env`).

So the env check should only apply to the GPU-requesting container, not the proxy. If you’d like, could you share the Pod YAML **after sidecar injection** (the running Pod), so we can confirm whether the annotation still matches the right container index? That would help us reproduce and rule out a mismatch in v2.5.1.

**Comment by bestend** [comment]
@Nimbus318 

I found a simpler way to reproduce this issue without involving the Linkerd-Proxy.
If you start the following pod, you’ll see that the CUDA container is still running with the HAMi core:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cuda-gpu-pod
spec:
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
    - name: cuda
      image: nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
      command: ["/bin/sleep", "infinity"]
      env:
        - name: CUDA_DISABLE_CONTROL
          value: "true"
      resources:
        limits:
          nvidia.com/gpu: "1"
```

Let me know if you need any more details or if you’d like further clarification!
