### ISSUE TITLE
Mismatch vGPU Memory actual allocate for K8s Pods

### ISSUE THREAD

**Issue by Xeus-Territory** [Project-HAMi/HAMi#1093]
**Please provide an in-depth description of the question you have**:

Hi, first of all, I'm unsure what's wrong with my configuration or internal HAMI, particularly the conflict with RKE2 Architecture. Please correct me if I'm wrong

We try to use HAMi for optimizing GPU relocation, and in a happy case, it works well and splits the GPU as a vGPU as expected, but

1. When `rke2-agent` of us restart in the GPU node (Incident in Infrastructure or other reasons), HAMI will keep continuous work, but the pod scheduled into that node, using the whole GPU instead of using vGPU in configuration.
2. I think there is something wrong with my configuration, but strange things, for example, my application has 3 replicates and is scheduled on **3 nodes with the same configuration** _(1 restarted node and 2 stable nodes)_

```
          resources:
            limits:
              memory: 2Gi
              nvidia.com/gpu: '1'
              nvidia.com/gpumem: '3500'
            requests:
              cpu: 200m
              memory: 2Gi
```
Two-node stable split right vGPU for the node

![Image](https://github.com/user-attachments/assets/1f1d01e3-2973-4f73-9991-788a882adffa)

But another one not split following vGPU, instead it uses the whole GPU for node **(NOTE: Because we have gpu-operator also, and if HAMI is not injected with mutation, that will relocate by Nvidia with the whole GPU)**

![Image](https://github.com/user-attachments/assets/f71c73ba-0cd3-40d2-a01e-0d6314a0d978)

Is something wrong in RKE2 configuration conflicting with HAMI Scheduler because there are no error logs inside HAMI Device Plugin and Schedule, but somehow HAMI is not injected

**What do you think about this question?**:
I think about the solution, and have a few insights in our case, maybe that can help you have more information, including

1. Because I met the error before, and the best case is restarting `daemonset` HAMI, which should load again `libvgpu.so` into again node

2. When I try to dive into node, I found `libvgpu.so` is compiled version and put in the location `usr/local/vgpu`, and there are `containers` directory inside node, where I can find containers split resource by HAMI, and more information will be logged into `kubelet` of RKE2 on `/var/lib/kubelet/device-plugins`, when I try to decode the script base64 inside, and I see HAMI is leveraging CUDA to assign the limit vGPU

3. RKE2 also uses containerd for running the service, so if I want to use a GPU, I need to follow their documentation at https://docs.rke2.io/advanced#deploy-nvidia-operator, and the HAMI documentation also at https://project-hami.io/docs/get-started/nginx-example#configure-containerd

When I look inside `systemctl` of `rke2-agent`, I see RKE2 uses `nvidia-container-cli` with `ld-kmod` loading. Is that able to help reload HAMI (libvgpu.so) into RKE2 after reload? I think that will let RKE2 continue to use HAMI for doing the task

**Environment**:
- HAMi version: v2.3.11
- Kubernetes version: RKE2 v1.27.11 
- Others:
    - Nvidia Driver: v535
    - GPU Operator: v23.6.1

**Comment by Xeus-Territory** [comment]
Hi @archlitchi, thank you for responding. The pod annotation and env inside the container are shown like

The annotation of pod not mounting `libvgpu.so` (NOTE: sorry, but we have some secrets in annotation, can share with you full)

```
  annotations:
    cni.projectcalico.org/containerID: xxxxxxxxxxx
    cni.projectcalico.org/podIP: xx.xx.xx.xx/32
    cni.projectcalico.org/podIPs: xx.xx.xx.xx/32
    hami.io/bind-phase: allocating
    hami.io/bind-time: '1747498472'
    hami.io/vgpu-devices-allocated: 'GPU-fa4d6262-0027-b2dd-395e-c181b50d6129,NVIDIA,3500,0:;'
    hami.io/vgpu-devices-to-allocate: 'GPU-fa4d6262-0027-b2dd-395e-c181b50d6129,NVIDIA,3500,0:;'
    hami.io/vgpu-node: prod-4070-1
    hami.io/vgpu-time: '1747498472'
    kubectl.kubernetes.io/restartedAt: '2025-05-17T16:14:11Z'
    nvidia.com/use-gputype: '4070'
    vault.hashicorp.com/agent-inject: ...
```

And the env (NOTE: still same annotation, some secret can be leaked so that I will remove a bit, sorry for inconvenience)

```
KUBERNETES_SERVICE_PORT_HTTPS=443
NVIDIA_VISIBLE_DEVICES=GPU-fa4d6262-0027-b2dd-395e-c181b50d6129
HOSTNAME=xxxxxxxxxxxxx
TERM=xterm
SHLVL=1
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

I think that all, if you need anything else, I will try to follow up. BTW, thank you
