### ISSUE TITLE
GPU Device Allocation Error: "unknown device" when using HAMi vGPU

### ISSUE THREAD

**Issue by Kevinz857** [Project-HAMi/HAMi#1106]
## Environment
- **HAMi Version**: v2.5.1
- **Kubernetes Version**: 1.31
- **GPU Driver Version**: NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     
- **Container Runtime**: containerd with nvidia runtime
- **GPU Model**: 4090
- **Node OS**: [Please specify OS version]

## Problem Description
Pod fails to start with `CrashLoopBackOff` status when using HAMi vGPU resource allocation. The nvidia-container-cli reports "unknown device" error for the GPU UUID allocated by HAMi.

## Error Message
```
nvidia-container-cli: device error: GPU-2409b7b6-2df6-0343-90dd-2d73da18e0e8: unknown device: unknown
```

## Pod Configuration
**Resource Requests:**
```yaml
resources:
  limits:
    nvidia.com/gpu: "1"
    nvidia.com/gpumem: "4096"
  requests:
    nvidia.com/gpu: "1"
    nvidia.com/gpumem: "4096"
```

**HAMi Annotations:**
```yaml
annotations:
  hami.io/bind-phase: success
  hami.io/bind-time: "1749138883"
  hami.io/vgpu-devices-allocated: GPU-2409b7b6-2df6-0343-90dd-2d73da18e0e8,NVIDIA:;
  hami.io/vgpu-devices-to-allocate: ;
  hami.io/vgpu-node: bare-xxxx-10-28-8-114
  hami.io/vgpu-time: "1749139149"
```

## Steps to Reproduce
1. Deploy a Pod with HAMi vGPU resource requests (`nvidia.com/gpu: "1"`, `nvidia.com/gpumem: "4096"`)
2. HAMi scheduler successfully allocates GPU device with UUID `GPU-2409b7b6-2df6-0343-90dd-2d73da18e0e8`
3. Pod binding phase shows `success` in annotations
4. Container runtime attempts to start the container
5. nvidia-container-cli fails to recognize the allocated GPU device UUID

## Expected Behavior
- Pod should start successfully with the allocated vGPU device
- Container should have access to the specified GPU memory (4096MB)
- No "unknown device" errors should occur

## Actual Behavior
- Pod enters `CrashLoopBackOff` state
- Container fails to start due to GPU device recognition failure
- Error indicates the GPU UUID allocated by HAMi is not recognized by nvidia-container-cli

## Additional Information

**Pod Status:**
```yaml
containerStatuses:
- lastState:
    terminated:
      exitCode: 128
      reason: StartError
      message: |-
        failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
        nvidia-container-cli: device error: GPU-2409b7b6-2df6-0343-90dd-2d73da18e0e8: unknown device: unknown
```

**Node Information:**
- Scheduled Node: `bare-xxxx-10-28-117`
- HAMi vGPU Node: `bare-xxxx-10-28-8-114`

## Possible Root Cause Analysis
1. **UUID Mismatch**: The GPU UUID generated/used by HAMi doesn't match the actual GPU device UUID recognized by the NVIDIA driver
2. **Device Plugin Communication**: Potential issue in communication between HAMi device plugin and nvidia-container-runtime
3. **GPU Device State**: The allocated GPU device might not be in the expected state or properly exposed to the container runtime
4. **Node Mismatch**: Notice that the scheduled node and HAMi vGPU node are different, which might indicate a scheduling inconsistency

## Debug Information Needed
To help diagnose this issue, please provide:
1. Output of `nvidia-smi -L` on the target node
2. HAMi device plugin logs from the affected node
3. HAMi scheduler logs during the pod scheduling
4. Output of `kubectl describe node <node-name>` for the affected node
5. HAMi configuration (ConfigMap/DaemonSet configuration)

## Workaround
Currently no known workaround. The issue prevents successful pod startup when using HAMi vGPU allocation.

---
**Labels**: bug, vgpu, device-allocation, nvidia, container-runtime
