### ISSUE TITLE
在一个k8s集群中，同时有t4卡和a100的卡，如何配置使t4使用hami core ,a100使用mig

### ISSUE THREAD

**Issue by cwdgit** [Project-HAMi/HAMi#1126]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- HAMi version: 2.5.2
- Kubernetes version: 1.23.3
- Others:

**Comment by Wangmin362** [comment]
可以参考链接：[用户指南共享 NVIDIA GPU 设备启用动态 MIG 功能](https://project-hami.io/zh/docs/userguide/NVIDIA-device/dynamic-mig-support)

目前hami只支持节点级别配置不同的模式，不支持显卡级别，可以参考下面的配置

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hami-device-plugin
  labels:
    app.kubernetes.io/component: hami-device-plugin
data:
  config.json: |
    {
        "nodeconfig": [
            {
                "name": "t4-node",
                "operatingmode": "hami-core",
                "devicememoryscaling": 1,
                "devicesplitcount": 10,
                "migstrategy":"none",
                "filterdevices": {
                  "uuid": [],
                  "index": []
                }
            },
          {
            "name": "a100-node",
            "operatingmode": "mig",
            "devicememoryscaling": 1,
            "devicesplitcount": 10,
            "migstrategy":"none",
            "filterdevices": {
              "uuid": [],
              "index": []
            }
          }
        ]
    }
```
