### ISSUE TITLE
vgpu不生效

### ISSUE THREAD

**Issue by Lai-JX** [Project-HAMi/HAMi#144]
部署完成后，相应的pod已经正常启动，如下图：
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/76830814/4be2bcde-2282-42bb-b4b2-0bfd24c3f88f)

但分配后的容器仍然占用了一整个gpu：
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/76830814/2ac179e4-1f72-4829-999b-415e3889a7c2)

容器的资源配置如下：
```yaml
resources:
  limits:
    cpu: 1
    memory: 10Gi
    nvidia.com/gpu: 1
    nvidia.com/gpucores: 30
    nvidia.com/gpumem: 300
  requests:
    cpu: 1
    memory: 10Gi
    nvidia.com/gpu: 1
    nvidia.com/gpucores: 30
    nvidia.com/gpumem: 300
```
值得注意的是，部署vgpu时，集群上已有一个占用2个gpu的pod。由于某些原因该pod无法终止，这会有影响吗？
总之，现在的vgpu无法生效
