### ISSUE TITLE
nvidia-smi 信息缺失

### ISSUE THREAD

**Issue by zlianzhuang** [Project-HAMi/HAMi#235]
nvidia-smi 在容器中，无法获得使用率和processes的进程信息。

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           Off | 00000000:00:06.0 Off |                    0 |
| N/A   31C    P0              37W / 250W |   2716MiB /  3000MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                          
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

宿主机： 可以获取
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           Off | 00000000:00:06.0 Off |                    0 |
| N/A   31C    P0              37W / 250W |   3338MiB / 16384MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                          
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     10495      C   python                                     3334MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by ls-2018** [comment]
- https://github.com/gpues/nvidia-pidns
你可以尝试这个组件

**Comment by lengrongfu** [comment]
> * https://github.com/gpues/nvidia-pidns
>   你可以尝试这个组件

```md
wget https://github.com/gpues/nvidia-pidns/releases/download/v0.0.1/nvidia-pidns.ko
insmod nvidia-pidns.ko
```

Excuse me, but after performing the above operations, can I see the process by executing `nvidia-smi` in the container? @ls-2018

**Comment by wawa0210** [comment]
This is a known issue. You cannot view the process information used through nvidia-smi in the container.

Some issue link i found
- https://github.com/NVIDIA/gpu-operator/issues/664
- https://github.com/NVIDIA/nvidia-docker/issues/179#issuecomment-242150861

Learned from the issue that it can be supported by **sharing host hostPID**,The test results are as follows

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    quota.kpanda.io/vgpu: '{"container-1":["nvidia-vgpu"]}'
  name: gpu-low-priority
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-low-priority
  template:
    metadata:
      annotations:
        quota.kpanda.io/vgpu: '{"container-1":["nvidia-vgpu"]}'
      labels:
        app: gpu-low-priority
    spec:
      hostPID: true
      containers:
      - args:
        - "6000"
        env:
        - name: CUDA_TASK_PRIORITY
          value: "1"
        image: chrstnhntschl/gpu_burn
        imagePullPolicy: IfNotPresent
        name: container-1
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpucores: "50"
            nvidia.com/gpumem: 3k
            nvidia.com/vgpu: "1"
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          privileged: false
```

Then, we can get process information by nvidia-smi in container

```bash
kubectl exec -it gpu-low-priority-5d5ddf4799-x7fvw nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[HAMI-core Msg(3812070:139664432936768:libvgpu.c:836)]: Initializing.....
Thu Apr 18 07:51:23 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P4                       On  | 00000000:1B:00.0 Off |                  Off |
| N/A   67C    P0              50W /  75W |      0MiB /  3000MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   3799297      C   /root/gpu_burn                             2822MiB |
|    0   N/A  N/A   3811857      C   /root/gpu_burn                              112MiB |
+---------------------------------------------------------------------------------------+
[HAMI-core Msg(3812070:139664432936768:multiprocess_memory_limit.c:434)]: Calling exit handler 3812070
```

We need to pay extra attention

- At this time, you can see all the process information consuming these GPU cards in the container, including other containers or the host. There is an "escape" risk
- Doesn’t know which processes in the list belong to the container
