### ISSUE TITLE
volcano schedule

### ISSUE THREAD

**Issue by Japson0** [Project-HAMi/HAMi#453]
I have a question, I saw that HAMI supports volcano, I read other issues, it only states that you can use the volcanic-device-plugin to support it. So I would like to ask can volcano match the HAMI plugin. Since pure vgpu doesn't quite fit our scenario, I wanted to use some of volcano's features and some of HAMI's features.
For example, the number of the GPU.
It looks like the following configuration
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job1
  namespace: emlp
  annotations:
    nvidia.com/use-gpuuuid: "GPU-123456"
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: test
        spec:
          containers:
            - image: nvidia/cuda:12.4.1-base-ubuntu22.04
              imagePullPolicy: IfNotPresent
              name: llama
              securityContext: 
               privileged: true 
              command: ["sleep"]
              args: ["100000"]
              resources:
                limits:
                  nvidia.com/gpu: 1
                  cpu: 3
          restartPolicy: OnFailure

```
