### ISSUE TITLE
Fix: Add NODE_NAME env var to vgpu-monitor container in Helm chart for nodeName retrieval

### ISSUE THREAD

**Issue by Nimbus318** [Project-HAMi/HAMi#686]
### Description:
The PR (#683) uses `nodeName := os.Getenv(util.NodeNameEnvName)` to retrieve the node name. However, the Helm chart does not set the `NODE_NAME` environment variable for the container. This causes nodeName to be empty when deployed via Helm.

### Proposed Solution:
Update the Helm chart to include the NODE_NAME environment variable by adding the following to the vgpu-monitor container spec:

```yaml
- name: NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
```
