### ISSUE TITLE
算力使用率数据异常

### ISSUE THREAD

**Issue by yuanssai** [Project-HAMi/HAMi#720]
**What happened**:

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/e6e923d0-f7cb-4f37-92f0-bf856a067c49" />
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/deb09c4c-0b4a-4fd3-98bc-a82e1450a56e" />
算力使用率数据异常，其他的数据都是正常的

**What you expected to happen**:
我希望数据回归正常

**How to reproduce it (as minimally and precisely as possible)**:
当我
        - name: CUDA_DISABLE_CONTROL
          value: "true"
的时候，pod指标都没有了，改成false就变成算力使用率异常

**Anything else we need to know?**:
这是我的deployment.yaml
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral-7b
  namespace: default
  labels:
    app: mistral-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mistral-7b
  template:
    metadata:
      labels:
        app: mistral-7b
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: pvc-mistral-7b
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "20Gi"
      containers:
      - name: mistral-7b
        image: vllm/vllm-openai:latest
        command: ["vllm", "serve", "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"]
        args: ["--trust-remote-code",""]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        - name: HF_HUB_ENABLE_HF_TRANSFER
          value: "0"
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 4
            nvidia.com/gpumem: 22000
            nvidia.com/gpucores: 95
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
EOF
```

pod 也是正常运行
