### ISSUE TITLE
[Ascend] 310P split not precise enough

### ISSUE THREAD

**Issue by mhh12121** [Project-HAMi/HAMi#748]
**Please provide an in-depth description of the question you have**:

I tried the following example:
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: swr.cn-south-1.myhuaweicloud.com/ascendhub/ascend-pytorch:24.0.RC1-A2-1.11.0-ubuntu20.04 
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          huawei.com/Ascend310P: 1 # requesting 1 Ascend
          huawei.com/Ascend310P-memory: 3500
```

assign `3500`  should be applied to `2/7` sharding, which should be `6144MB` ;

However, use `npu-smi info` got kinda weird result

as shown below: `5381MB` is the max memory allocated? 

```
+--------------------------------------------------------------------------------------------------------+
| npu-smi 24.1.rc2                                 Version: 24.1.rc2                                     |
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Name                  | Health          | Power(W)     Temp(C)           Hugepages-Usage(page) |
| Chip    Device                | Bus-Id          | AICore(%)    Memory-Usage(MB)                        |
+===============================+=================+======================================================+
| 40      310Pvir02             | OK              | NA           39                0     / 0             |
| 0       0                     | 0000:03:00.0    | 0            450  / 5381                             |
+===============================+=================+======================================================+
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Chip                  | Process id      | Process name             | Process memory(MB)        |
+===============================+=================+======================================================+
| No running processes found in NPU 40                                                                   |
+===============================+=================+======================================================+

```

And the log from `Hami-scheduler` container `vgpu-externder`

```
I1227 08:38:21.176052       1 util.go:277] "Decoded pod annos" poddevices={"Ascend310P":[[{"Idx":0,"UUID":"Ascend310P-0","Type":"Ascend310P","Usedmem":6144,"Usedcores":0}]]}

```
shows that it did allocate with  `2/7`= 6144 strategy

**What do you think about this question?**:

Why I got the above `5381` value, how is it calculated? Is it owing to Ascend310P itself issue?

**Environment**:
Env:
Hami: v2.4.0

Hami-ascend-device-plugin: v1.0.0

OS: OpenEuler 22.03 SP1 , 5.10.0-136.12.0.86.oe2203sp1.aarch64

k8s: v1.23.7

containerd: v1.6.4

Ascenddriver: 24.1Rc2

Ascendcontainerruntime: 6.0.RC3

Ascend product: 300i Pro

**Comment by archlitchi** [comment]
Ascend 310p uses pre-defined slices for device-sharing,  the corresponding templates for 310p is shown in the link below: https://www.hiascend.com/document/detail/zh/computepoweralloca/300/cpaug/cpaug/cpaug_00005.html, in its document, the device memory 'vir02' instance is 6G. You can adjust the template in ConfigMap hami-schduler-device, to make it more fitting to your environment

**Comment by mhh12121** [comment]
@archlitchi Thanks for ur response! I did use the default template as shown below:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-hami-scheduler-device
  labels:
    app.kubernetes.io/component: hami-scheduler
    helm.sh/chart: hami-2.4.0
    app.kubernetes.io/name: hami
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "2.4.0"
    app.kubernetes.io/managed-by: Helm
data:
  ascend-config.yaml: |-
    vnpus:
    - chipName: 910B
      commonWord: Ascend910A
      resourceName: huawei.com/Ascend910A
      resourceMemoryName: huawei.com/Ascend910A-memory
      memoryAllocatable: 32768
      memoryCapacity: 32768
      aiCore: 30
      templates:
        - name: vir02
          memory: 2184
          aiCore: 2
        - name: vir04
          memory: 4369
          aiCore: 4
        - name: vir08
          memory: 8738
          aiCore: 8
        - name: vir16
          memory: 17476
          aiCore: 16
    - chipName: 910B3
      commonWord: Ascend910B
      resourceName: huawei.com/Ascend910B
      resourceMemoryName: huawei.com/Ascend910B-memory
      memoryAllocatable: 65536
      memoryCapacity: 65536
      aiCore: 20
      aiCPU: 7
      templates:
        - name: vir05_1c_16g
          memory: 16384
          aiCore: 5
          aiCPU: 1
        - name: vir10_3c_32g
          memory: 32768
          aiCore: 10
          aiCPU: 3
    - chipName: 310P3
      commonWord: Ascend310P
      resourceName: huawei.com/Ascend310P
      resourceMemoryName: huawei.com/Ascend310P-memory
      memoryAllocatable: 21527
      memoryCapacity: 24576
      aiCore: 8
      aiCPU: 7
      templates:
        - name: vir01
          memory: 3072
          aiCore: 1
          aiCPU: 1
        - name: vir02
          memory: 6144
          aiCore: 2
          aiCPU: 2
        - name: vir04
          memory: 12288
          aiCore: 4
          aiCPU: 4
```

As far as i know, the `memory: 6144` should occur in `npu-smi info`  ?
But let's check the info I posted, the mem usage is: `450  / 5381`, does it work as expected?
