### ISSUE TITLE
When devicePlugin.passDeviceSpecsEnabled is set to true, GPU pod failed to start (failed to apply OCI options)

### ISSUE THREAD

**Issue by Rei1010** [Project-HAMi/HAMi#776]
**What happened**:
Install HAMi helm with default options, GPU pod failed to run with error "Error: failed to generate container "180e8893b52ae58994b7db777ee79513fbf6555e10d49cb686f94e8f88666074" spec: failed to apply OCI options: lstat /dev/nvidiactl: no such file or directory"

(https://github.com/Project-HAMi/HAMi/blob/b8548c3c5250107f7427340d76f6f7e2aa653ccb/charts/hami/values.yaml#L139)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Just install HAMi with latest code and it reproduced

**Anything else we need to know?**:

Test yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1 # declare how many physical GPUs the pod needs
          nvidia.com/gpumem: 3000 # identifies 3000M GPU memory each physical GPU allocates to the pod （Optional,Integer）
          nvidia.com/gpucores: 30 # identifies 30% GPU GPU core each physical GPU allocates to the pod （Optional,Integer)

```

Enable passDeviceSpecsEnabled
![image](https://github.com/user-attachments/assets/c0126727-193f-4c68-9e5d-0eb16adc8e2a)

Disable passDeviceSpecsEnabled
![image](https://github.com/user-attachments/assets/f5df5c43-7c40-4eb8-8a81-6606e78d7a64)

Related PR:
https://github.com/Project-HAMi/HAMi/pull/690

**Environment**:
- HAMi version:
- nvidia driver or other AI device driver version:
- Docker version from `docker version`
- Docker command, image and tag used
- Kernel version from `uname -a`
- Others:
