### ISSUE TITLE
can't scheduler the resource for pod, shows :err="0/1 nodes are available: 1 node unregistered."

### ISSUE THREAD

**Issue by leven87** [Project-HAMi/HAMi#815]
**What happened**:
I use kubenete 1.23.1, and install Hami followed the guide by default as below:
```sh
helm install hami hami-charts/hami --set scheduler.kubeScheduler.imageTag=v1.23.1 -n kube-system
```
then I try the default_use.yaml to test ：
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  schedulerName: hami-scheduler
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 vGPUs
#          nvidia.com/gpumem: 3000 # Each vGPU contains 3000m device memory （Optional,Integer）
#          nvidia.com/gpucores: 30 # Each vGPU uses 30% of the entire GPU （Optional,Integer)
```
I see the pod is keep pending, and use `kubectl describe pod gpu-pod` command to see the below warnings:
```
Events:
  Type     Reason            Age                 From            Message
  ----     ------            ----                ----            -------
  Warning  FailedScheduling  18m                 hami-scheduler  0/1 nodes are available: 1 node unregistered.
  Warning  FailedScheduling  16m (x1 over 17m)   hami-scheduler  0/1 nodes are available: 1 node unregistered.
  Warning  FilteringFailed   11s (x14 over 18m)  hami-scheduler  no available node, all node scores do not meet
```
**What you expected to happen**:
it schudules the pod successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

- The output of `nvidia-smi -a` on your host
![image](https://github.com/user-attachments/assets/989d7f49-0db0-4814-b63b-10f92427594a)

- Your docker or containerd configuration file (e.g: `/etc/docker/daemon.json`)
- The hami-device-plugin container logs
![image](https://github.com/user-attachments/assets/b2effd14-aa93-44e3-9581-29b47614de4f)

- The hami-scheduler container logs
![image](https://github.com/user-attachments/assets/95d1c934-248f-4cc5-a1f8-5903fc75e811)
- The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
- Any relevant kernel output lines from `dmesg`

**Environment**:
- HAMi version: hami-2.4.1
- nvidia driver or other AI device driver version: 
- Docker version from `docker version`
- Docker command, image and tag used
- Kernel version from `uname -a`
- Others:
