### ISSUE TITLE
pod分配问题请教

### ISSUE THREAD

**Issue by ruoniler** [Project-HAMi/HAMi#882]
**Please provide an in-depth description of the question you have**:

我这边有一个节点，两张T4 GPU卡，安装了2.5版本的HAMI
当前存在一个疑问：我跑了两个测试pod，申请vgpu=1，显存申请一个3G一个5G，我想要的效果是**自动**只在一张卡上分配这两个pod所需要的显存然后，但是实际效果是用到了两张卡，这不就导致了显存碎片化了吗？具体信息如下图所示

![Image](https://github.com/user-attachments/assets/99d375b2-f427-41f0-9c1b-ac731b5ffb21)
![Image](https://github.com/user-attachments/assets/0685e950-991a-4b21-928d-a5fabc779299)
![Image](https://github.com/user-attachments/assets/0f0dbd86-9172-4ae7-95a6-98ba02f3d3ac)
![Image](https://github.com/user-attachments/assets/3edaa4fd-2be4-4b21-9b8f-8e73323abfef)

**What do you think about this question?**:

**Environment**:
- HAMi version:2.5
- Kubernetes version:1.25.0
- Others:

**Comment by ruoniler** [comment]
> 可以考虑配置相关的分配策略，详见文档： https://github.com/Project-HAMi/HAMi/blob/ac6292d55fc43c83a0e0ff5b2351793abbe35fb7/docs/config_cn.md
> 
> ```
> scheduler.defaultSchedulerPolicy.gpuSchedulerPolicy：字符串类型，预设值为 "spread" 表示 GPU 调度策略， "binpack"表示尽量将任务分配到同一个 GPU 上，"spread"表示尽量将任务分配到不同 GPU 上。
> ```
yaml中定义annotations的pod调度策略为binpack，但是仍然没有效果。经过测试当yaml中定义为pod而不是job时可以正常按照binpack模式分配。

**Comment by ruoniler** [comment]
HAMI是不是不支持Job类型的pod调度？如果支持应该如何设置和使用？

**Comment by Nimbus318** [comment]
@ruoniler 对于 deploy、sts、ds、job、cj，这些资源，`annotations` 必须放在 `spec.template.metadata` 下才能生效

比如：
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job
spec:
  template:
    metadata:
      annotations:
        hami.io/gpu-scheduler-policy: "binpack"  # 在 template.metadata 中定义 annotation
    spec:
      containers:
      - name: gpu-container
        image: your-image
        ...
```
