### ISSUE TITLE
多实例之后，GPU资源请求失效，只有设置了gpumem才能正常调度

### ISSUE THREAD

**Issue by ThinkBlue1991** [Project-HAMi/HAMi#888]
下面是测试分别设置nvidia/gpu、nvidia/gpu+gpumem、nvidia/gpu+gpucores三种情况的调度，

发现只有nvidia/gpu+gpumem全部设置才能够正常调度，和虚拟出来的多张卡感觉关系不大，

请问这是什么问题？

- 服务器有两张1080Ti的物理卡
```
# nvidia-smi
Thu Feb 20 08:32:10 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti     Off |   00000000:02:00.0 Off |                  N/A |
| 21%   27C    P8              9W /  250W |       2MiB /  11264MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce GTX 1080 Ti     Off |   00000000:83:00.0 Off |                  N/A |
| 21%   32C    P8             10W /  250W |       2MiB /  11264MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

```
- 部署hami之后，虚拟出vgpu共20张卡
```
Capacity:
  cpu:                56
  ephemeral-storage:  284641736Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131872976Ki
  nvidia.com/gpu:     20
  pods:               110
Allocatable:
  cpu:                56
  ephemeral-storage:  262325823464
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131770576Ki
  nvidia.com/gpu:     20
  pods:               110

```
- 创建3个pod,每个pod使用一个gpu卡
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-3
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
```
- 结果显示，第三个实例的时候，pod处于pending 状态
```
# kubectl get pod
NAME                          READY   STATUS      RESTARTS      AGE
dnsutils                      1/1     Running     1 (52d ago)   115d
gpu-pod-1                     1/1     Running     0             26s
gpu-pod-2                     1/1     Running     0             12s
gpu-pod-3                     0/1     Pending     0             4s
```
- 重新删除以上三个pod,再在pod创建中，增加gpumem
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-7
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem: 3000
```
- 重新创建pod,可以创建6个，第7个pod 处于pending，每张卡可以分配3*3000MB的pod,这个是正常的
```
# kubectl get pod
NAME                          READY   STATUS      RESTARTS      AGE
dnsutils                      1/1     Running     1 (52d ago)   115d
gpu-pod-1                     1/1     Running     0             82s
gpu-pod-2                     1/1     Running     0             91s
gpu-pod-3                     1/1     Running     0             102s
gpu-pod-4                     1/1     Running     0             60s
gpu-pod-5                     1/1     Running     0             43s
gpu-pod-6                     1/1     Running     0             15s
gpu-pod-7                     0/1     Pending     0             7s
```

- 删除pod,设置gpucores
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-3
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
            #nvidia.com/gpumem: 3000
          nvidia.com/gpucores: 30
```
- 重新创建pod,可以创建2个，第3个pod 处于pending
```
# kubectl get pod
NAME                          READY   STATUS      RESTARTS      AGE
dnsutils                      1/1     Running     1 (52d ago)   115d
gpu-pod-1                     1/1     Running     0             14s
gpu-pod-2                     1/1     Running     0             8s
gpu-pod-3                     0/1     Pending     0             2s

```
