### ISSUE TITLE
Used ResourceQuota doesn't calculated correctly

### ISSUE THREAD

**Issue by zhengtianbao** [Project-HAMi/HAMi#893]
**What happened**:
I have create a namespace ResourceQuota:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: xudawen
  name: xudawen
spec:
  hard:
    requests.nvidia.com/gpucore: 25
    requests.nvidia.com/gpumemory: 6000
```
and test.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: xudawen
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpumem: 7000 # identifies 3000M GPU memory each physical GPU allocates to the pod （Optional,Integer）
          nvidia.com/gpucores: 30 # identifies 30% GPU GPU core each physical GPU allocates to the pod （Optional,Integer)
```
and execute: kubectl apply -f test.yaml

**What you expected to happen**:

I want to limit gpumemory max to 6000MiB at this namespace, and used ResourceQuota can show correctly.

**How to reproduce it (as minimally and precisely as possible)**:

![Image](https://github.com/user-attachments/assets/c6f25c24-bad9-4266-939e-d73bf47abc02)

**Environment**:
- HAMi version: 2.5.0
