### ISSUE TITLE
add resource rename like nvidia-device-plugin

### ISSUE THREAD

**Issue by shoted** [Project-HAMi/HAMi#992]
add resource rename like nvidia-device-plugin

config.yaml
```
version: v1
resources: 
  gpus:
  - pattern: 'Tesla V100'
     name: nvidia.com/gpu-v100
```

node
```
Allocatable:
  nvidia.com/gpu:        0
  nvidia.com/gpu-v100:   20
  pods:                  200
```

**Comment by archlitchi** [comment]
resourcename can be configured according to document here: https://project-hami.io/docs/userguide/configure/

**Comment by shoted** [comment]
I hope rename from device name like 

```
version: v1
resources: 
  gpus:
  - pattern: 'Tesla V100'
     name: nvidia.com/gpu-v100
  - pattern: 'Tesla T4'
     name: nvidia.com/gpu-t4
```
